zad1: 1.c 1_palindrom.c
	clang 1.c 1_palindrom.c -Wextra --pedantic -std=c11 -o 1

zad2: 2.c 2_f.c
	clang 2.c 2_f.c -Wextra --pedantic -std=c11 -lm -o 2

zad3: 3.c 3_phi.c
	clang 3.c 3_phi.c -Wextra --pedantic -std=c11 -lm -o 3

zad4: 4.c agents.c
	clang 4.c agents.c -Wextra --pedantic -std=c11 -lm -o 4